version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    
  userservice:
    build: ./userservice
    depends_on:
      - postgres
    # environment:
    #   - DB_URL=jdbc:postgresql://postgres:5432/user_db
    #   - DB_USERNAME=postgres
    #   - DB_PASSWORD=postgres
  
  productservice:
    build: ./productservice
    depends_on:
      - postgres
    # environment:
    #   - DB_URL=jdbc:postgresql://postgres:5432/products_db
    #   - DB_USERNAME=postgres
    #   - DB_PASSWORD=postgres

  orderservice:
    build: ./orderservice
    depends_on:
      - postgres
    # environment:
    #   - DB_URL=jdbc:postgresql://postgres:5432/orders_db
    #   - DB_USERNAME=postgres
    #   - DB_PASSWORD=postgres

  cartservice:
    build: ./cartservice
    depends_on:
      - postgres
    # environment:
    #   - DB_URL=jdbc:postgresql://postgres:5432/orders_db
    #   - DB_USERNAME=postgres
    #   - DB_PASSWORD=postgres

  apigateway:
    build: ./apigateway
    ports:
      - "8080:8080"
    depends_on:
      - userservice
      - productservice
      - orderservice
      - cartservice