CREATE DATABASE products_db;
CREATE DATABASE orders_db;
CREATE DATABASE user_db;
CREATE DATABASE cart_db;

-- INSERT INTO ROLES(name) VALUES ('ROLE_USER');
-- INSERT INTO ROLES(name) VALUES ('ROLE_ADMIN');