### Base URL
@baseUrl = http://localhost:8080/ecommerce/api/cart

@token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlcjFAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImlhdCI6MTc3NzU0Nzk4MiwiZXhwIjoxNzc3NTgzOTgyfQ.QGSKCiriy_1EcvmZmx4hJBzhUr-DNJsLKjE6Li5xyR0

### Add item to cart
POST {{baseUrl}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "userId": 1,
    "productId": 1,
    "quantity": 2
}


### Get cart items for a user
GET {{baseUrl}}/1
Authorization: Bearer {{token}}


### Get cart items for a user
GET {{baseUrl}}/1/batch
Authorization: Bearer {{token}}


### Remove item from cart
DELETE {{baseUrl}}/1/1
Authorization: Bearer {{token}}


### Remove item from cart
DELETE {{baseUrl}}/1
Authorization: Bearer {{token}}