### Base URL
@baseUrl = http://localhost:8080/ecommerce/api/products

@token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlcjFAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImlhdCI6MTc3NzQ2ODAwOSwiZXhwIjoxNzc3NTA0MDA5fQ.dlqcSqVNzxcyiiKC0CqUl_jK3i0MWTw226F6XfOgDS8


### Create new product
POST {{baseUrl}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Product1",
    "description": "Description of product 1",
    "price": 10,
    "quantity": 100
}


### Get All products
GET {{baseUrl}}
Content-Type: application/json
Authorization: Bearer {{token}}


### Get Product by Id
GET {{baseUrl}}/1
Content-Type: application/json
Authorization: Bearer {{token}}


