server:
  port: 8080

spring:
  cloud:
    gateway:
      default-filters:
        - PreserveHostHeader
      routes:
        - id: userservice
          uri: http://userservice:8081
          predicates:
            - Path=/ecommerce/api/auth/**

        - id: productservice
          uri: http://productservice:8082
          predicates:
            - Path=/ecommerce/api/products/**

        - id: orderservice
          uri: http://orderservice:8083
          predicates:
            - Path=/ecommerce/api/orders/**

        - id: cartservice
          uri: http://cartservice:8084
          predicates:
            - Path=/ecommerce/api/cart/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: 
              - "https://glorious-zebra-vpvrw5g77p4v2wr7x-3000.app.github.dev"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
