spring.application.name=userservice

server.port=8081

# Database configuration
# spring.datasource.url=jdbc:postgresql://localhost:5432/user_db
spring.datasource.url=jdbc:postgresql://postgres:5432/user_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=3yhn4crncrc48yn4cs34324Dsw434encb373BNaMpDWe334n2738aMp