spring.application.name=orderservice

server.port=8083

# Database configuration
# spring.datasource.url=jdbc:postgresql://localhost:5432/orders_db
spring.datasource.url=jdbc:postgresql://postgres:5432/orders_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=3yhn4crncrc48yn4cs34324Dsw434encb373BNaMpDWe334n2738aMp